<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <ArtifactsPath>$(BaseArtifactsPath)\$(MSBuildThisFileName)</ArtifactsPath>
    <PublishDir>$(ArtifactsPath)</PublishDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JsonPatch.Net" />
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Platform\Kuiper.Plaform.ManagementObjects\Kuiper.Plaform.ManagementObjects.csproj" />
    <ProjectReference Include="..\..\Platform\Kuiper.Plaform.ServiceApi\Kuiper.Plaform.ServiceApi.csproj" />
    <ProjectReference Include="..\..\ServiceInfra\Kuiper.ServiceInfra.Configuration\Kuiper.ServiceInfra.Configuration.csproj" />
    <ProjectReference Include="..\..\ServiceInfra\Kuiper.ServiceInfra.Hosting\Kuiper.ServiceInfra.Hosting.csproj" />
    <ProjectReference Include="..\..\ServiceInfra\Kuiper.ServiceInfra.Persistence\Kuiper.ServiceInfra.Persistence.csproj" />
    <ProjectReference Include="..\..\ServiceInfra\Kuiper.ServiceInfra.Security\Kuiper.ServiceInfra.Security.csproj" />
  </ItemGroup>
</Project>
