name: Build & Test

on:
  workflow_dispatch:
  
  schedule:
    - cron: '30 6 * * *'
  push:
    branches: [ "main", "develop", "next", "next-major" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  DOTNET_VERSION: 8.0.205

jobs:
  build:
#    needs: version
#    strategy:
#      matrix:
#        configuration: [Debug, Release]

    runs-on: ubuntu-latest   # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: '5.x'

    - name: Version
      id: version_step
      uses: gittools/actions/gitversion/execute@v1.1.1
      with:
        useConfigFile: true

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore Packages
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test --no-restore --configuration Release

    - name: Check if working directory exists
      run: |
        if [ ! -d "src/Kuiper.Clustering.ServiceApi/bin/Release" ]; then
          echo "Directory src/Kuiper.Clustering.ServiceApi/bin/Release does not exist."
          exit 1
        fi

    - name: Clear Docker build cache
      run: docker builder prune -f

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image (Dev)
      if: ${{ github.ref != 'refs/heads/main' }}
      uses: docker/build-push-action@v4
      with:
        context: src/Kuiper.Clustering.ServiceApi
        push: true
        build-args: |
          BUILD_CONFIG=Release
        tags: |
          ${{ secrets.ACR_LOGIN_SERVER }}/kuiper-service-api:${{ env.majorMinorPatch }}.${{ env.commitsSinceVersionSource }}-dev-${{ env.shortSha }}

    - name: Build and push Docker image (Main)
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: docker/build-push-action@v4
      with:
        context: src/Kuiper.Clustering.ServiceApi
        push: true
        build-args: |
          BUILD_CONFIG=Release
        tags: |
          ${{ secrets.ACR_LOGIN_SERVER }}/kuiper-service-api:latest
          ${{ secrets.ACR_LOGIN_SERVER }}/kuiper-service-api:${{ env.majorMinorPatch }}.${{ env.commitsSinceVersionSource }}-${{ env.shortSha }}